# Generated by Django 2.1.7 on 2019-04-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='adress',
            new_name='address',
        ),
    ]
