# Generated by Django 2.1.3 on 2019-04-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190415_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('stock_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opi', to='core.StockProduct')),
            ],
        ),
    ]
