# Generated by Django 2.1.4 on 2019-04-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190419_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='core.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sample_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
