# Generated by Django 2.1.3 on 2019-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderproductinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='entrance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
