# Generated by Django 2.1.5 on 2019-04-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190409_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address',
        ),
        migrations.AddField(
            model_name='addresses',
            name='building',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addresses',
            name='city',
            field=models.TextField(default='Москва'),
        ),
        migrations.AddField(
            model_name='addresses',
            name='entrance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='flat',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addresses',
            name='street',
            field=models.TextField(default='Довженко'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
