# Generated by Django 2.1.3 on 2019-04-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190425_1614'),
        ('core', '0004_auto_20190421_1939'),
    ]

    operations = [
    ]
