# Generated by Django 2.1.5 on 2019-04-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190409_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
