# Generated by Django 2.1.5 on 2019-04-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190412_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.TextField(default='Рассматривается'),
        ),
    ]
