# Generated by Django 2.1.5 on 2019-05-07 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_merge_20190425_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
