# Generated by Django 2.1.4 on 2019-04-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_main_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='sample_image',
        ),
        migrations.RemoveField(
            model_name='stockproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_image', to='core.Product'),
        ),
        migrations.AddField(
            model_name='images',
            name='stock_product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.StockProduct'),
        ),
    ]
