# Generated by Django 2.1.4 on 2019-04-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
