# Generated by Django 2.1.4 on 2019-04-29 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190429_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_product', to='core.Product'),
        ),
    ]
