# Generated by Django 2.1.3 on 2019-05-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20190425_1737'),
        ('core', '0014_auto_20190429_1233'),
    ]

    operations = [
    ]
