# Generated by Django 2.1.4 on 2019-05-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20190501_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='building',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
