# Generated by Django 2.1.4 on 2019-05-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190508_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
