# Generated by Django 2.1.3 on 2019-05-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190508_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='core.Product'),
        ),
    ]
