# Generated by Django 2.1.4 on 2019-05-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190508_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='description',
            field=models.TextField(default='Дом'),
        ),
    ]
