# Generated by Django 2.1.4 on 2019-05-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190510_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='building',
            field=models.TextField(default='1'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='flat',
            field=models.TextField(default='1'),
        ),
    ]
