# Generated by Django 2.1.4 on 2019-05-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190515_1736'),
        ('core', '0022_auto_20190515_1654'),
    ]

    operations = [
    ]
