# Generated by Django 2.1.4 on 2019-05-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20190515_1745'),
        ('core', '0019_auto_20190517_1639'),
    ]

    operations = [
    ]
