# Generated by Django 2.1.4 on 2019-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_order_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
